# Generated by Django 4.2 on 2023-06-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_cu_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cu_profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='cu_profile',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='cu_profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cu_profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='li_images'),
        ),
    ]
