# Generated by Django 4.2 on 2023-06-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_lr_addbook_bookdesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lr_addbook',
            old_name='bookdesc',
            new_name='bookDescription',
        ),
        migrations.RemoveField(
            model_name='lr_addbook',
            name='date',
        ),
    ]
