# Generated by Django 4.2 on 2023-06-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_rename_bookdesc_lr_addbook_bookdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lr_addbook',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
