# Generated by Django 4.2 on 2023-06-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_alter_lr_addbook_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lr_addbook',
            name='image',
        ),
    ]
