# Generated by Django 4.2 on 2023-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_remove_lr_addbook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lr_addbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bookadd'),
        ),
    ]
