# Generated by Django 4.2 on 2023-06-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0012_lr_addbook_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('startdate', models.DateField(auto_now_add=True)),
                ('phoneno', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='lr_addbook',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
