# Generated by Django 4.2 on 2023-06-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0013_book_rent_alter_lr_addbook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_rent',
            name='startdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
