# Generated by Django 4.2 on 2023-06-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0014_alter_book_rent_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_rent',
            name='bookname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
