# Generated by Django 4.2 on 2023-06-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0015_book_rent_bookname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=255, null=True)),
                ('email', models.CharField(max_length=10000)),
                ('message', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
