# Generated by Django 4.2 on 2023-06-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_rent',
            name='HowMAnyDaysYouNeed',
            field=models.IntegerField(null=True),
        ),
    ]
